### ISSUE TITLE
При запуске приложения ничего не происходит

### ISSUE THREAD

**Issue by flalex** [wasd171/chatinder#3]
1. Скачал по ссылке https://chatinder.herokuapp.com/download/win32
2. Запустил дабл кликом.
3. Открылось приложение с пустым окном. Ничего не происходит.
![image](https://user-images.githubusercontent.com/818999/27469296-d1bf2ff4-57ff-11e7-889d-8c8ffa00b540.png)

P.S. Устанавливал на win 8.1 64x

**Comment by wasd171** [comment]
Можете попробовать скачать версию из [релизов](https://github.com/wasd171/chatinder/releases)? 
Звучит странно, я постараюсь разобраться.

**Comment by pozitronik** [comment]
Подтверждаю проблему, Win10x64, запускалось в т.ч. с админскими правами.

**Comment by wasd171** [comment]
@flalex , @pozitronik : вы не могли бы проверить, починил ли я проблему в версии 1.5.0?

**Comment by pozitronik** [comment]
Да, запускается авторизация и открываются чаты.

**Comment by wasd171** [comment]
Closed by https://github.com/wasd171/chatinder/commit/f6aca6ab50fa9182b60636dafb0e0d5b4f63f543
