### ISSUE TITLE
Добавь пожалуйста инструкции для сборки (зависимости и т.д.). Спасибо

### ISSUE THREAD

**Issue by quentincaffeino** [wasd171/chatinder#5]

**Comment by wasd171** [comment]
```
npm install
npm run publish
```
Эти команды соберут приложение. Для сборки в режиме разработки используйте `npm run build:dev`

Добавлю в README

**Comment by wasd171** [comment]
Для запуска приложения введите `NODE_ENV=development node_modules/.bin/electron .`

**Comment by QuentinCaffeino** [comment]
Благодарю

**Comment by QuentinCaffeino** [comment]
Какую версию npm ты используешь?

**Comment by wasd171** [comment]
`npm@4`, у пятой версии раньше были какие-то баги, может с `npm@5.1` можно будет переехать

**Comment by QuentinCaffeino** [comment]
Неудалось собрать)
node@6.10 LTS, npm@3.10.10
OS: elementary 0.4.1 Loki, Ubuntu 16.04, Debian 9 stretch/sid
[npm install](https://pastebin.com/yiPg0z4D) (https://pastebin.com/yiPg0z4D)
[npm run publish](https://pastebin.com/MUDWjHF5) (https://pastebin.com/MUDWjHF5)

Потом попробую обновится)

**Comment by wasd171** [comment]
Я не пробовал собирать под Linux, пока всё сложно с автообновлением там. Похоже на баг [electron-builder](https://github.com/electron-userland/electron-builder)

**Comment by QuentinCaffeino** [comment]
Не по делу: ох уж этот ноджс :D
